name: client-node
env:
  CI: true

on:
  push:
    # paths:
    #   - '**.ts'
  workflow_dispatch:
    inputs:
      version:
        description: 'either of patch, minor, major.'
        required: true
        default: 'patch'
    branches: [ main ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com'

      - name: Display version of Node.js, npm
        run: |
          node --version
          npm --version

      - name: install
        run: npm install

      - name: lint
        run: npm run lint

      - name: build
        run: npm run build

      - name: test
        run: npm run test

  publish:
    name: publish
    needs: test
    # if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com'

      - name: Display version of Node.js, npm
        run: |
          node --version
          npm --version

      - name: git config
        run: |
          git config --global user.name Release Bot
          git config --global user.email bot@sshort.link

      - name: bump version
        run: |
          VERSION=${{ github.event.inputs.version }}
          VERSION=${VERSION:-patch}
          case "${VERSION}" in
            "patch" )
              npm version patch
              ;;
            "minor" )
              npm version minor
              ;;
            "major" )
              npm version major
              ;;
            * )
              exit 1
              ;;
          esac

      - name: install
        run: npm install

      - name: build
        run: npm run build

      - name: publish
        run: |
          npx can-npm-publish --verbose && npm publish || echo "Does not publish"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: Release Bot # defaults to "GitHub Actions"
          commit_user_email: bot@sshort.link # defaults to "actions@github.com"

      # Push tag to GitHub if package.json version's tag is not tagged
      - name: package-version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: package-version-to-git-tag
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          version: ${{ env.PACKAGE_VERSION }}
