name: client-node
env:
  CI: true

on:
  push:
    # paths:
    #   - '**.ts'
  workflow_dispatch:
    inputs:
      version:
        description: 'either of patch, minor, major.'
        required: true
        default: 'patch'
    branches: [ main ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com'
      - name: Display version of Node.js, npm
        run: |
          node --version
          npm --version
      - name: install
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        run: npm run test

  publish:
    name: publish
    needs: test
    # if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com'
      - name: Display version of Node.js, npm
        run: |
          node --version
          npm --version
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: bump version
        run: |
          case ${{ github.event.inputs.version }} in
          "patch")
            npm version patch
            ;;
          "minor")
            npm version minor
            ;;
          "major")
            npm version major
            ;;
          *)
            exit 1
            ;;
          esac
      - name: publish
        run: |
          npx can-npm-publish --verbose && npm publish || echo "Does not publish"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
      # Push tag to GitHub if package.json version's tag is not tagged
      - name: package-version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - name: package-version-to-git-tag
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          version: ${{ env.PACKAGE_VERSION }}
